DROP TABLE PERSON;
CREATE TABLE PERSON (CUSTOMER_ID INTEGER NOT NULL, CITY VARCHAR(255), "NAME" VARCHAR(255), "STATE" VARCHAR(255), PRIMARY KEY (CUSTOMER_ID));
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (1, 'Alanta', 'Small Bill Company', 'GA');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (2, 'San Mateo', 'Bob Hosting Corp.', 'CA');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (3, 'San Jose', 'Early CentralComp', 'CA');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (4, 'Dearborn', 'West Valley Inc.', 'MI');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (5, 'Dearborn', 'Zed Motor Co', 'MI');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (6, 'New York', 'Old Media Productions', 'NY');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (7, 'New York', 'Yankee Computer Repair Ltd', 'NY');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (8, 'Clarksburg', 'Jim', 'WV');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (9, 'Bb', 'Bob', 'Ca');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (10, 'Morgantown', 'Jim', 'WV');
INSERT INTO APP.PERSON (CUSTOMER_ID, CITY, "NAME", "STATE") 
	VALUES (11, 'Coolest Town', 'Beau', 'Wv');
